### PR TITLE
Add style suggestion to use keyword args for 3 or more args in function call

### PR DESCRIPTION
**Pull request by johnmanong**
see title.

### CODE REVIEW

**Comment by jnak** [comment]
I like that! Could we enforce that with a lint rule?

**Comment by johnmanong** [comment]
@jnak we could certainly write one (didn't see any built into pylint); thought this would be a good start

**Comment by johnmanong** [comment]
@ianschenck thoughts?

**Comment by ianschenck** [comment]
A few thoughts here:

I think the goal here, most generally, is that people should write clear code. More specifically, this rule tries to clarify function calls by forcing keyword argument use when there are many. There's a lot of talk about this in "Effective Python", and I don't disagree. However, this could be pretty restrictive and isn't totally airtight.

Finally,this could steer people in the wrong direction when it comes to things like Thrift (and implementations), which cross language boundaries and have undefined behavior around keyword arguments.

That said, I'm fine with it as a _recommendation_, though I don't want my linter yelling at me when I've written concise code. Advice-level lint might be ok?

**Comment by ianschenck** [comment]
I think maybe a counter example when keyword arguments might not be strictly necessary could be beneficial:

```
move_to(x_coordinate, y_coordinate, speed_per_second)
```

Pretty clear, because all of the arguments are well-named.

**Comment by johnmanong** [comment]
@ianschenck done

**Pull request merged**
